"""Coloured Triangles
https://www.codewars.com/kata/coloured-triangles

If you finish this kata, you can try [Insane Coloured Triangles](http://www.codewars.com/kata/insane-coloured-triangles) by Bubbler, which is a harder version of this one.

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

For example, different possibilities are:
```
Colour here:            G G        B G        R G        B R
Becomes colour here:     G          R          B          G
```

With a bigger example:
```
R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
```

You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given 'RRGBRGBB' you should return 'G'.

* The input string will only contain the uppercase letters 'B', 'G' or 'R' and there will be at least one letter so you do not have to test for invalid input.
* If you are only given one colour as the input, return that colour.


*Adapted from the 2017 British Informatics Olympiad*
"""


def update_row(row):
    rule = {
        'BB': 'B',
        'GG': 'G',
        'RR': 'R',
        'BG': 'R',
        'GR': 'B',
        'BR': 'G',
    }
    return ''.join(
        rule.get(''.join(sorted(row[i]+row[i+1]))) for i in range(len(row)-1))

def triangle(row):
    while len(row) > 1:
        row = update_row(row)
    return row
